require('../../../fix-dns.js');
const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const timetableRoutes = require('./routes/timetableRoutes');
const app = express();
app.use(express.json());
app.use(cors());
app.use('/', timetableRoutes);
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'timetable-service' }));
connectDB(process.env.MONGO_URI || 'mongodb://localhost:27017/edusphere_timetable');
app.listen(3009, () => console.log('Timetable Service running on 3009'));