const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const libraryRoutes = require('./routes/libraryRoutes');
const app = express();
app.use(express.json());
app.use(cors());
app.use('/', libraryRoutes);
app.get('/health', (req, res) => res.json({ status: 'ok', service: 'library-service' }));
connectDB(process.env.MONGO_URI || 'mongodb://localhost:27017/edusphere_library');
app.listen(3011, () => console.log('Library Service running on 3011'));