const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const calendarRoutes = require('./routes/calendarRoutes');
const app = express();
app.use(express.json());
app.use(cors());
app.use('/', calendarRoutes);
app.get('/health', (req, res) => res.json({ status: 'UP' }));
connectDB(process.env.MONGO_URI || 'mongodb://localhost:27017/edusphere_calendar');
app.listen(3010, () => console.log('Calendar Service running on 3010'));